"use client";

import "./globals.css";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";

const metadata = {
  title: "Google Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className="relative min-h-screen">
        {children}
        {pathname === "/" && <Footer />}
      </body>
    </html>
  );
};