import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Search Engine App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        {children}
        <Footer />
      </body>
    </html>
  );
}
